### ISSUE TITLE
Hogwarts Legacy SUB-enUS.bin and MAIN-deDE.bin

### ISSUE THREAD

**Issue by nyswiftiewthlftpb** [pragma-one-over-two/avafdict-codec#1]
Input file: SUB-enUS.bin
Output file: SUB-enUS.bin.decoded.txt
Traceback (most recent call last):
  File "avafdict_decode.py", line 54, in <module>
  File "avafdict_decode.py", line 48, in main
  File "avafdict_decode.py", line 26, in decode
  File "encodings\utf_16_le.py", line 16, in decode
UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 20-21: illegal UTF-16 surrogate
[9516] Failed to execute script 'avafdict_decode' due to unhandled exception!

**Every other language files work, Thank You!**

**Comment by pragma-one-over-two** [comment]
Hi,

Seems there's a problem with the file's header, which is weirdly unlikely considering it works for other language files... and SUB-enUS is no different from the others. Perhaps try extracting it again, or open it and check if the header is similar to the other files. It should start with a rather readable "AVAFDICT 2.0":

![image](https://user-images.githubusercontent.com/49337497/223865637-f51e5c70-5029-4172-a72a-879967e3d4f8.png)
![image](https://user-images.githubusercontent.com/49337497/223866042-7cb968ed-71c6-45e0-8638-74baf896bf2b.png)

The script doesn't even check the header, it only displays it, but an issue at this point would hint at a corrupted file. I'll switch it to a more friendly ASCII encoding regardless, so it no longer crashes and prints the header, which in the future may help identify corrupted files.

In the eventuality that your tool used for extracting files does it wrong, I'd recommend FModel as a user-friendly, tried-and-true tool for extracting data from Hogwarts Legacy: https://fmodel.app/

Regards.

**Comment by pragma-one-over-two** [comment]
Script has been updated, try it again. If all else fails, upload your SUB-enUS.bin here and I'll check it.

That is, if that issue is still blocking a week later. Sorry about that late response, hopefully you found a workaround in the meantime 😉
